# values/mlflow-values.yaml
backendStore:
  type: sqlite
  config:
    database: /mlflow-data/mlflow.db

defaultArtifactRoot: /mlflow-artifacts

service:
  type: ClusterIP
  port: 5000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
