# application/mlflow-application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow-app
  namespace: infra-tools
spec:
  project: default
  source:
    repoURL: https://community-charts.github.io/helm-charts
    chart: mlflow
    targetRevision: 0.6.2
    helm:
      valueFiles:
        - values/mlflow-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: mlflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
